apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-kamu-ingress
  namespace: app-kamu-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: app-kamu.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-kamu-service
                port:
                  number: 3000

  tls:
    - hosts:
        - app-kamu.domain.com
      secretName: app-kamu-tls